- hosts: localhost
  become: true

  tasks:
  - name: AddPPARepositories
    apt_repository:
        validate_certs: no
        repo: 'ppa:flexiondotorg/quickemu'
        state: present
  - name: Install Linux packages
    apt:
      name:
      - python3-pip
      - nodejs
      - npm
      - git
      - firefox
      - quickemu
      - gnome-tweaks
  - name: Install python packages
    pip:
      name:
       - bpytop
       - ansible
