- hosts: localhost
  become: true

  tasks:
  - name: create download/ansible directory
    file:
      path: /home/sysdevpc/Downloads/ansible
      state: directory
      mode: '0774'
      recurse: yes

  - name: download Atom File
    get_url: 
      url: https://atom.io/download/deb
      dest: /home/ubuntutestvm/Downloads/ansible

  - name: install atom from deb file
    apt: deb="/home/ubuntutestvm/Downloads/ansible/atom-amd64.deb"


  - name: download VScode
    get_url: 
      url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
      dest: /home/ubuntutestvm/Downloads/ansible

  - name: install atom from deb file
    apt: deb="/home/ubuntutestvm/Downloads/ansible/code_1.61.2-1634656828_amd64.deb"

  - name: download VSCoduim
    get_url: 
      url: https://github.com/VSCodium/vscodium/releases/download/1.61.2/codium_1.61.2-1634689349_amd64.deb
      dest: /home/ubuntutestvm/Downloads/ansible

  - name: install VSCodium  from deb file
    apt: deb="/home/ubuntutestvm/Downloads/ansible/codium_1.61.2-1634689349_amd64.deb"

  - name: download Google Chrome
    get_url: 
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /home/ubuntutestvm/Downloads/ansible

  - name: install google chrome
    apt: deb="/home/ubuntutestvm/Downloads/ansible/google-chrome-stable_current_amd64.deb"

  - name: Add PPA Repositories
    apt_repository:
        validate_certs: no
        repo: 'ppa:flexiondotorg/quickemu'
        state: present
  
  - name: Install Linux packages
    apt:
      name:
      - python3-pip
      - nodejs
      - npm
      - git
      - firefox
      - quickemu
      - gnome-tweaks
      - terminator
      - chromium-browser
      - gnome-session gdm3
      - tasksel
      - ubuntu-desktop
      - gnome-shell-extensions
  - name: Install python packages
    pip:
      name:
       - bpytop
       - ansible
